---
# defaults file for kibana

## server settings
server_port: 5601
server_host: 0.0.0.0
server_name: kibana

## elasticsearch hosts
elasticsearch_host: http://localhost:9200

kibana_username: kbnAdmin
kibana_password: A!@#kibana

