---
# tasks file for elasticserach_provisioning
- name: Servers IPs
  debug:
    msg: '{{ ansible_host }}'

- name: Installing JAVA
  apt:
    name: openjdk-8-jdk
  
- name: Import the Elasticsearch PGP Keyedit
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present
  
- name: Adding Elasticsearch APT repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present

- name: Update repositories cache and install ELASTICSEARCH    
  apt:
    name: elasticsearch
    update_cache: yes

- name: Replace default elasticsearch.yml
  template:
   src: elasticsearch.yml.j2
   dest: /etc/elasticsearch/elasticsearch.yml

- name: Enable service elasticsearch
  service:
    name: elasticsearch
    enabled: yes

- name: Start Elasticsearch Service
  service:
    name: elasticsearch
    state: started

# Xpack secuity configuration

- name: create elasticsearch keystore
  command: >
    {{ elasticsearch_home }}/bin/elasticsearch-keystore create
  args:
    creates: "{{ elasticsearch_conf_dir }}/elasticsearch.keystore"
  environment:
    ES_CONF_PATH: "{{ elasticsearch_conf_dir }}"

- name: Set elasticsearch keystore permissions
  file: state=file path={{ elasticsearch_conf_dir }}/elasticsearch.keystore owner=elasticsearch group=root mode=0660

- name: Check if elasticsearch keystore is setup  
  command: >
   {{ elasticsearch_home }}/bin/elasticsearch-keystore list
  register: result
  changed_when: False
  environment:
    ES_CONF_PATH: " {{ elasticsearch_conf_dir }} "
  check_mode: no

- name: Create bootstrap password for elastic user
  become: yes
  shell: echo "{{ elasticsearch_auth_password }}" | {{ elasticsearch_home }}/bin/elasticsearch-keystore add -x 'bootstrap.password'
  when:
   - elasticsearch_auth_username is defined and result is defined and elasticsearch_auth_username == 'elastic' and 'bootstrap.password' not in result.stdout_lines
  environment:
    ES_CONF_PATH: " {{ elasticsearch_conf_dir }} "
  no_log: true

- name: Restarting elasticsearch service
  service:
    name: elasticsearch
    state: restarted
