# Playbook to install the Elastic Search

---
- hosts: all
  become: yes
  become_user: root
  gather_facts: true
  vars_files: 
  - ./vars/credentials.yml

  roles:
    - common
    - elasticserach_provisioning